In [1]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
bisayuk_dataset = pd.read_csv ('DATA MHS.csv')

In [3]:
bisayuk_dataset.head()

NAMA          NIM        PRODI  SPK  DATA MINING  \
0          Muhammad Vika Wava    193200061  Informatika    0           85   
1             Alviahtu Zakiah   1900018235  Informatika   85            0   
2                 Qoyum Milati  1900018244  Informatika   70           85   
3              M Dhiyaul Lami    193200052  Informatika   89           85   
4  Muhammad rosyad dzikrillah    193200060  Informatika   85           89   

   PEMROG  MACHINE  OUTCOME  
0      70       70        1  
1      85        0       -1  
2      70       72        1  
3      50       85       -1  
4      89       85        1

In [4]:
bisayuk_dataset.shape

(261, 8)

In [5]:
bisayuk_dataset['OUTCOME'].value_counts()

OUTCOME
 1    209
-1     47
 0      5
Name: count, dtype: int64

In [6]:
X = bisayuk_dataset.drop(["NAMA ","NIM","PRODI","OUTCOME"],axis=1)

In [8]:
Y = bisayuk_dataset['OUTCOME']
print(X)

     SPK  DATA MINING  PEMROG  MACHINE
0      0           85      70       70
1     85            0      85        0
2     70           85      70       72
3     89           85      50       85
4     85           89      89       85
..   ...          ...     ...      ...
256   88           90      90       75
257   89           90      90       80
258   90           89      89       78
259   76           87      87       90
260   89           88      88       75

[261 rows x 4 columns]


In [9]:
print(Y)

0      1
1     -1
2      1
3     -1
4      1
      ..
256    1
257    1
258    1
259    1
260    1
Name: OUTCOME, Length: 261, dtype: int64


In [10]:
scaler = StandardScaler()

In [11]:
scaler.fit(X)

StandardScaler()

In [12]:
standarized_data = scaler.transform(X)

In [13]:
print(standarized_data)

[[-3.87373477  0.17662233 -0.74795073 -1.21312071]
 [ 0.33668147 -4.54430108  0.18017197 -8.48468086]
 [-0.40633316  0.17662233 -0.74795073 -1.00536185]
 ...
 [ 0.58435301  0.39878343  0.42767135 -0.38208526]
 [-0.10912731  0.28770288  0.30392166  0.86446791]
 [ 0.5348187   0.34324316  0.36579651 -0.69372355]]


In [15]:
X = standarized_data
Y = bisayuk_dataset['OUTCOME']

In [16]:
print(X)
print(Y)

[[-3.87373477  0.17662233 -0.74795073 -1.21312071]
 [ 0.33668147 -4.54430108  0.18017197 -8.48468086]
 [-0.40633316  0.17662233 -0.74795073 -1.00536185]
 ...
 [ 0.58435301  0.39878343  0.42767135 -0.38208526]
 [-0.10912731  0.28770288  0.30392166  0.86446791]
 [ 0.5348187   0.34324316  0.36579651 -0.69372355]]
0      1
1     -1
2      1
3     -1
4      1
      ..
256    1
257    1
258    1
259    1
260    1
Name: OUTCOME, Length: 261, dtype: int64


In [17]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2,stratify=Y,random_state=2)

In [18]:
print(X.shape,X_train.shape,X_test.shape)

(261, 4) (208, 4) (53, 4)


In [19]:
classifier = svm.SVC(kernel='linear')

In [20]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [21]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

In [22]:
print('Akurasi Data Training adalah = ',training_data_accuracy)

Akurasi Data Training adalah =  0.8028846153846154


In [23]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [24]:
print('Akurasi Data Testing adalah = ',test_data_accuracy)

Akurasi Data Testing adalah =  0.7924528301886793


In [25]:
input_data = (0, 85,70,	70)
input_data_as_numpy_array = np.array(input_data)
input_data_reshape = input_data_as_numpy_array.reshape(1,-1)
std_data = scaler.transform(input_data_reshape)
print(std_data)
prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0]==0):
    print('Rekomendasi RPL')
else:
    print('Rekomendasi Data')

[[-3.87373477  0.17662233 -0.74795073 -1.21312071]]
[1]
Rekomendasi Data


c:\Users\User\MANUAL\.venv\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [26]:
import pickle
filename = 'bisayuk_model.sav'
pickle.dump(classifier, open(filename,'wb'))